docs: enable srs commands and add documentation
redhat-developer/app-services-cli pull request #1105
Opened 2021-09-22 16:43 UTC by wtrocki

This PR enables Service Registry commands to be visible by default. 
It also adds documentation for service registry.

We should not merge that before service registry is merged in UI and getting overall approval. 
I have created special prerelease for testing.

2021-09-22 16:45 UTC, wtrocki commented
Documentation needs fixes:

```
PUNCTUATION_RULE Command rhoas -> Flag - version: usage - Show rhoas version
PUNCTUATION_RULE Command rhoas cluster bind -> Flag - app-name: usage - Name of the kubernetes deployment to bind
PUNCTUATION_RULE Command rhoas cluster bind -> Flag - bind-env: usage - Bind service as environment variables
PUNCTUATION_RULE Command rhoas cluster bind -> Flag - binding-name: usage - Name of the Service binding object to create when using operator
PUNCTUATION_RULE Command rhoas cluster bind -> Flag - deployment-config: usage - Use DeploymentConfig to detect your application
PUNCTUATION_RULE Command rhoas cluster bind -> Flag - ignore-context: usage - Ignore currently selected services and ask to select each service separately
PUNCTUATION_RULE Command rhoas cluster bind -> Flag - kubeconfig: usage - Location of the kubeconfig file
PUNCTUATION_RULE Command rhoas cluster bind -> Flag - namespace: usage - Custom Kubernetes namespace (if not set current namespace will be used)
PUNCTUATION_RULE Command rhoas cluster bind -> Flag - yes: usage - Forcibly create a binding without confirmation
PUNCTUATION_RULE Command rhoas cluster connect -> Flag - ignore-context: usage - Ignore currently selected services and ask to select each service separately
PUNCTUATION_RULE Command rhoas cluster connect -> Flag - kubeconfig: usage - Location of the kubeconfig file
PUNCTUATION_RULE Command rhoas cluster connect -> Flag - namespace: usage - Custom Kubernetes namespace (if not set current namespace will be used)
PUNCTUATION_RULE Command rhoas cluster connect -> Flag - token: usage - Provide an offline token to be used by the operator (to get a token, visit https://console.redhat.com/openshift/token)

PUNCTUATION_RULE Command rhoas cluster connect -> Flag - yes: usage - Forcibly create a binding without confirmation
PUNCTUATION_RULE Command rhoas cluster status -> Flag - kubeconfig: usage - Location of the kubeconfig file
PUNCTUATION_RULE Command rhoas kafka consumer-group delete -> Flag - id: usage - The unique ID of the consumer group to delete
PUNCTUATION_RULE Command rhoas kafka consumer-group delete -> Flag - yes: usage - Skip confirmation to forcibly delete a consumer group
PUNCTUATION_RULE Command rhoas kafka consumer-group describe -> Flag - id: usage - The unique ID of the consumer group to view
PUNCTUATION_RULE Command rhoas kafka consumer-group describe -> Flag - output: usage - Format in which to display the consumer group (choose from: "json", "yml", "yaml")
PUNCTUATION_RULE Command rhoas kafka consumer-group list -> Flag - output: usage - Format in which to display the consumer group (choose from: "json", "yml", "yaml")
PUNCTUATION_RULE Command rhoas kafka consumer-group list -> Flag - page: usage - Current page number for list of consumer groups
PUNCTUATION_RULE Command rhoas kafka consumer-group list -> Flag - search: usage - Text search to filter consumer groups by ID
PUNCTUATION_RULE Command rhoas kafka consumer-group list -> Flag - size: usage - Maximum number of consumer groups to be returned per page
PUNCTUATION_RULE Command rhoas kafka consumer-group list -> Flag - topic: usage - Fetch the consumer groups for a specific Kafka topic
PUNCTUATION_RULE Command rhoas kafka consumer-group reset-offset -> Flag - id: usage - The unique ID of the consumer group to reset-offset
PUNCTUATION_RULE Command rhoas kafka consumer-group reset-offset -> Flag - offset: usage - Offset type (choose from: "earliest", "latest", "absolute", "timestamp")
PUNCTUATION_RULE Command rhoas kafka consumer-group reset-offset -> Flag - output: usage - Format in which to display reset offset result (choose from: "json", "yml", "yaml")
PUNCTUATION_RULE Command rhoas kafka consumer-group reset-offset -> Flag - partitions: usage - Partitions on which to reset the consumer group offset (comma-separated integers)
PUNCTUATION_RULE Command rhoas kafka consumer-group reset-offset -> Flag - topic: usage - Select topic for which consumer group offsets are to be reset
PUNCTUATION_RULE Command rhoas kafka consumer-group reset-offset -> Flag - value: usage - Custom offset value (required when offset is "absolute" or "timestamp")
PUNCTUATION_RULE Command rhoas kafka consumer-group reset-offset -> Flag - yes: usage - Skip confirmation to forcibly reset the offset for the consumer group
PUNCTUATION_RULE Command rhoas kafka topic create -> Flag - cleanup-policy: usage - Determines whether log messages are deleted, compacted, or both
PUNCTUATION_RULE Command rhoas kafka topic create -> Flag - name: usage - Topic name
PUNCTUATION_RULE Command rhoas kafka topic create -> Flag - output: usage - Format in which to display the Kafka topic (choose from: "json", "yml", "yaml")
PUNCTUATION_RULE Command rhoas kafka topic create -> Flag - partitions: usage - The number of partitions in the topic
PUNCTUATION_RULE Command rhoas kafka topic create -> Flag - retention-bytes: usage - The maximum total size of a partition log segments before old log segments are deleted to free up space
PUNCTUATION_RULE Command rhoas kafka topic create -> Flag - retention-ms: usage - The period of time in milliseconds the broker will retain a partition log before deleting it
PUNCTUATION_RULE Command rhoas kafka topic delete -> Flag - name: usage - Topic name
PUNCTUATION_RULE Command rhoas kafka topic delete -> Flag - yes: usage - Skip confirmation to forcibly delete a topic
PUNCTUATION_RULE Command rhoas kafka topic describe -> Flag - name: usage - Format in which to display the Kafka topic (choose from: "json", "yml", "yaml")
PUNCTUATION_RULE Command rhoas kafka topic describe -> Flag - output: usage - Format in which to display the Kafka topic (choose from: "json", "yml", "yaml")
PUNCTUATION_RULE Command rhoas kafka topic list -> Flag - output: usage - Format in which to display the Kafka topic (choose from: "json", "yml", "yaml")
PUNCTUATION_RULE Command rhoas kafka topic list -> Flag - page: usage - Current page number for list of topics
PUNCTUATION_RULE Command rhoas kafka topic list -> Flag - search: usage - Text search to filter the Kafka topics by name
PUNCTUATION_RULE Command rhoas kafka topic list -> Flag - size: usage - Maximum number of items to be returned per page
PUNCTUATION_RULE Command rhoas kafka topic update -> Flag - cleanup-policy: usage - Determines whether log messages are deleted, compacted, or both
PUNCTUATION_RULE Command rhoas kafka topic update -> Flag - name: usage - Topic name
PUNCTUATION_RULE Command rhoas kafka topic update -> Flag - output: usage - Format in which to display the Kafka topic (choose from: "json", "yml", "yaml")
PUNCTUATION_RULE Command rhoas kafka topic update -> Flag - partitions: usage - The number of partitions in the topic
PUNCTUATION_RULE Command rhoas kafka topic update -> Flag - retention-bytes: usage - The maximum total size of a partition log segments before old log segments are deleted to free up space
PUNCTUATION_RULE Command rhoas kafka topic update -> Flag - retention-ms: usage - The period of time in milliseconds the broker will retain a partition log before deleting it
PUNCTUATION_RULE Command rhoas kafka create -> Flag - name: usage - Unique name of the Kafka instance
PUNCTUATION_RULE Command rhoas kafka create -> Flag - output: usage - Format in which to display the Kafka instance (choose from: "json", "yml", "yaml")
PUNCTUATION_RULE Command rhoas kafka create -> Flag - provider: usage - Cloud Provider ID
PUNCTUATION_RULE Command rhoas kafka create -> Flag - region: usage - Cloud Provider Region ID
PUNCTUATION_RULE Command rhoas kafka create -> Flag - use: usage - Set the new Kafka instance to the current instance
PUNCTUATION_RULE Command rhoas kafka create -> Flag - wait: usage - Wait until the Kafka instance is created
PUNCTUATION_RULE Command rhoas kafka delete -> Flag - id: usage - Unique ID of the Kafka instance you want to delete
PUNCTUATION_RULE Command rhoas kafka delete -> Flag - name: usage - Name of the Kafka instance you want to delete [...]

2021-09-22 18:00 UTC, smccarthy-ie commented on docs/commands/rhoas_service-registry_artifact.adoc
> +This command is available as part of the developer preview
Suggest the following (occurs in multiple files):
This command is available as part of the Development Preview release.

2021-09-22 18:00 UTC, smccarthy-ie commented on docs/commands/rhoas_service-registry_role.adoc
> +Roles can be applied to users and service accounts generated by cli (service account ids
Suggest: 
Roles can be applied to users and service accounts generated by the CLI (service account IDs).

These commands are only accessible to users with the organization admin role or owners of the Service Registry instance.

This command is available as part of the Development Preview release.

2021-09-23 07:09 UTC, rkpattnaik780 requested changes
Currently the `rhoas status` command doesn't show status of service-registry by default. It should be available already.

2021-09-23 11:10 UTC, wtrocki commented
Good guy charmil saved us tons of verification again! Thx @ankithans

2021-09-23 11:24 UTC, rkpattnaik780 approved these changes

2021-09-23 11:32 UTC, merged