Use pre-defined service status constant values
redhat-developer/app-services-cli pull request #1178
Opened 2021-10-04 19:07 UTC by kashifsoofi

Closes #1174 

### Verification Steps

1. Do x
2. Do y

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change
- [ ] Other (please specify)

### Checklist

- [ ] Documentation added for the feature
- [ ] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

2021-10-04 19:19 UTC, wtrocki commented
Amazing contribution. @craicoverflow will review

2021-10-05 08:05 UTC, craicoverflow approved these changes
Thank you very much. In future though, can you please fill out the description and verification steps 👍🏻

2021-10-05 08:05 UTC, craicoverflow approved these changes

2021-10-05 08:08 UTC, craicoverflow requested changes
Thank you so much! The build is failing. You need to run `make docs/generate`.

Also, we follow conventional commits. Please read the CONTRIBUTING guidelines for more: https://github.com/redhat-developer/app-services-cli/blob/main/CONTRIBUTING.md#best-practices

2021-10-05 09:48 UTC, merged