feat(service-registry): add description flag for create command
redhat-developer/app-services-cli pull request #1344
Opened 2021-12-08 11:53 UTC by rkpattnaik780

Add `--description` flag to `service-registry create` command.

### Verification Steps
1. Try creating a service registry instance with description flag.
```
rhoas service-registry create --name test-instance --description "random description"
```
2. Create a registry instance through interactive mode:
```
rhoas service-registry create
```

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change
- [ ] Other (please specify)

### Checklist

- [X] Documentation added for the feature
- [X] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

2021-12-09 12:53 UTC, craicoverflow requested changes
A question about validation left inline. One thing I think that we _need_ is multiline descriptions. Verified and works great otherwise.

2021-12-09 12:53 UTC, craicoverflow commented on pkg/localize/locales/en/cmd/registry_crud.en.toml
> +one = 'Description of Service Registry instance [optional]:'
```suggestion
one = 'Description [optional]:'
```

Simply "Description" should be enough, like we do with Kafka. It should be clear from the context already.

2021-12-09 12:53 UTC, craicoverflow commented on pkg/cmd/registry/create/create.go
> +	err = survey.AskOne(promptDescription, &answers.Description)
It is likely that a description is long, possibly multiline. We need to ensure that the user can create a multi-line description.

2021-12-10 16:34 UTC, wtrocki commented
Also when doing edit we should always have description available as empty string:

rhoas service-registry artifact metadata-set --artifact-id=test

Does

```
{
 "labels": [],
 "properties": {}
}
```

It should

```
{
 "description": "",
 "labels": [],
 "properties": {}
}
```

2021-12-15 08:03 UTC, wtrocki approved these changes

2021-12-16 13:01 UTC, craicoverflow commented
I see this was approved, so I guess it should be merged?

2021-12-16 13:01 UTC, craicoverflow approved these changes

2021-12-16 14:38 UTC, wtrocki commented
I tend to leave PRs that were previously rejected by one team member for them to take look if they are happy with resolution. I'm certainly are so merging :D

2021-12-16 14:38 UTC, merged