Connectors v2 Feature
redhat-developer/app-services-cli pull request #1635
Opened 2022-07-11 20:12 UTC by wtrocki

Feature branch for connectors v2 commands

2022-07-11 20:12 UTC, wtrocki commented
#requires rebase

2022-07-12 09:12 UTC, jackdelahunt commented
@wtrocki are we merging this?

2022-07-12 09:53 UTC, wtrocki commented
@jackdelahunt that is feature branch. Feature branch are rebased periodically. 
They can be used to review strings and aggregate all PRs. This would be merged when we finish **all** requirements for phase2. We have PR for visibility and collaboration.

2022-07-12 16:27 UTC, MelissaFlinn requested changes
Looks good overall. Let me know if you have any questions...

2022-07-12 16:27 UTC, MelissaFlinn commented on pkg/core/localize/locales/en/cmd/connectors.toml
> +# Select a connector instance by name to be set in the current context
Set the current Connectors instance by providing the name of a Connectors instance.

2022-07-12 16:27 UTC, MelissaFlinn commented on pkg/core/localize/locales/en/cmd/connectors.toml
> +# Select a connector instance by ID to be set in the current context
Set the current Connectors instance by providing the ID of a Connectors instance.

2022-07-12 16:27 UTC, MelissaFlinn commented on pkg/core/localize/locales/en/cmd/connectors.toml
> +description = "Error message for when and connector with ID is not found"
Error message for when a Connectors instance ID is not found

2022-07-12 16:27 UTC, MelissaFlinn commented on pkg/core/localize/locales/en/cmd/connectors.toml
> +description = "Error message for when and connector with name is not found"
Error message for when a Connectors instance name is not found

2022-07-12 16:27 UTC, MelissaFlinn commented on pkg/core/localize/locales/en/cmd/context.en.toml
> +# Select a connector instance by name to be set in the current context
Set the current Connectors instance by providing the name of a Connectors instance.

2022-07-12 16:27 UTC, MelissaFlinn commented on pkg/core/localize/locales/en/cmd/context.en.toml
> +# Select a connector instance by ID to be set in the current context
Set the current Connectors instance by providing the ID of a Connectors instance.

2022-07-12 16:27 UTC, MelissaFlinn commented on pkg/core/localize/locales/en/cmd/context.en.toml
> +Use the "rhoas context set-connector" command to select a connector instance for your context
The Connectors instance for the current context is not set. The `rhoas` CLI uses the current Connectors instance when you run any `rhoas connector cluster` commands.
Use the `rhoas context set-connector` command to set the current Connectors instance.

2022-07-13 11:14 UTC, MelissaFlinn commented
Is there/will there be a command that the user can run that returns the name and ID of the current Connectors instance?

2022-07-15 10:35 UTC, jackdelahunt commented
@MelissaFlinn We added connectors to the cli's context so the current working connector is always known and the user can get details about it easily with `rhoas context status connector`. They can also get details of all connectors they have with `rhoas connector list`.

2022-07-18 12:14 UTC, merged