feat: addition of descriptions and examples to dedicated
redhat-developer/app-services-cli pull request #1801
Opened 2023-01-30 12:27 UTC by dimakis

Closes # 

### Verification Steps

1. Do x
2. Do y

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change
- [ ] Other (please specify)

2023-01-30 17:23 UTC, rkpattnaik780 requested changes
Dropping few suggestions. It is good to run `make generate-docs` when changes are made for command descriptions.

2023-01-30 17:23 UTC, rkpattnaik780 commented on pkg/core/localize/locales/en/cmd/dedicated.en.toml
> +# register-cluster, registers an OpenShift cluster with Red Hat OpenShift Streams for Apache Kafka.
```suggestion
# Register an OpenShift cluster with Red Hat OpenShift Streams for Apache Kafka
```

2023-01-30 17:23 UTC, rkpattnaik780 commented on pkg/core/localize/locales/en/cmd/dedicated.en.toml
> +rhoas cluster register-cluster
```suggestion
rhoas dedicated register-cluster
```

2023-01-31 08:36 UTC, dimakis commented
@rkpattnaik780 all comments have been addressed... 😄

2023-01-31 09:56 UTC, rkpattnaik780 commented on pkg/core/localize/locales/en/cmd/dedicated.en.toml
> +one = 'Manage your OpenShift clusters to use with Red Hat OpenShift Streams for Apache Kafka.'
Remove the `.`

2023-03-08 09:24 UTC, closed without merging