Add custom cluster mgmt url flag
redhat-developer/app-services-cli pull request #1803
Opened 2023-02-03 12:42 UTC by dimakis

This allows the user to specify a custom api-gateway for their clustermgmt (ocm) which allows the CLI to install stage Addons if the targeted KFM deployment is stage.

Closes # 

### Verification Steps

1. Do x
2. Do y

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change
- [ ] Other (please specify)

2023-02-03 21:12 UTC, machi1990 commented on pkg/cmd/dedicated/register/registercluster.go
> +	err = createAddonWithParams(opts, getKafkaFleetManagerAddonIdByEnv(con), response.FleetshardParameters)
```suggestion
	err = createAddonWithParams(opts, getKafkaFleetShardAddonIdByEnv(con), response.FleetshardParameters)
```

2023-02-03 21:12 UTC, machi1990 commented on pkg/cmd/dedicated/register/registercluster.go
> +func getKafkaFleetManagerAddonIdByEnv(con *config.Config) string {
```suggestion
func getKafkaFleetShardAddonIdByEnv(con *config.Config) string {
```

2023-02-03 21:16 UTC, machi1990 reviewed
left one suggestion on function name.

reviewed the change, it responds to MVP requirement.
In the near term future, let's progress the conversation about KFM having a metadata API that drives most of the things here.

2023-02-07 09:30 UTC, machi1990 requested changes
hi @dimakis this is semi unrelated but can we sort out the wording in https://github.com/redhat-developer/app-services-cli/blob/5f68f800ab0d67d90c34301aede29fc9a767e838/pkg/core/localize/locales/en/cmd/dedicated.en.toml#L29

it should read `Kafkas` and not `Kakfas`  thanks ;-)

2023-02-08 09:08 UTC, machi1990 requested changes
The lines https://github.com/redhat-developer/app-services-cli/blob/5f68f800ab0d67d90c34301aede29fc9a767e838/pkg/cmd/dedicated/register/registercluster.go#L386-L390 are inversed.

It should be 
```go
if accessKafkasViaPublicNetwork {
		opts.accessKafkasViaPrivateNetwork = true
	} else {
		opts.accessKafkasViaPrivateNetwork = false
	}
```
or simply 
```go
opts.accessKafkasViaPrivateNetwork=accessKafkasViaPublicNetwork
```

While we are at it, the whole method can be refactored to
```go
prompt := &survey.Confirm{
		Message: opts.f.Localizer.MustLocalize("dedicated.registerCluster.prompt.selectPublicNetworkAccess.message"),
		Help:    opts.f.Localizer.MustLocalize("dedicated.registerCluster.prompt.selectPublicNetworkAccess.help"),
		Default: opts.accessKafkasViaPrivateNetwork,
	}
	err := survey.AskOne(prompt, &opts.accessKafkasViaPrivateNetwork)
	if err != nil {
		return err
	}
return nil
```

2023-02-08 10:02 UTC, dimakis commented
> 

do you suspect that a private network will be the default? the reason I have that as is, is that I presumed public would be default. This was also mentioned by Keith Wall. I'm easy either way really.

2023-02-08 10:11 UTC, machi1990 commented
> > 
> 
> @machi1990 do you suspect that a private network will be the default? the reason I have that as is, is that I presumed public would be default. This was also mentioned by Keith Wall. I'm easy either way really.

Hi @dimakis there is a bug in that logic which I highlighted. If someone choose to allow for private kafkas - i.e `accessKafkasViaPublicNetwork set to "true"` then with the logic current in place, it'll send the value as `false`. And vice versa.

2023-02-08 10:13 UTC, machi1990 commented
> > 
> 
> @machi1990 do you suspect that a private network will be the default? the reason I have that as is, is that I presumed public would be default. This was also mentioned by Keith Wall. I'm easy either way really.

Also note: the suggested fix does not change the default value.

2023-02-08 10:16 UTC, dimakis commented
> > @machi1990 do you suspect that a private network will be the default? the reason I have that as is, is that I presumed public would be default. This was also mentioned by Keith Wall. I'm easy either way really.
> 
> Hi @dimakis there is a bug in that logic which I highlighted. If someone choose to allow for private kafkas - i.e `accessKafkasViaPublicNetwork set to "true"` then with the logic current in place, it'll send the value as `false`. And vice versa.

@machi1990 It is not a bug, its a feature 😛 
The wording is changed to public, i.e. `would you like your kafkas to have access to a public network` hence the inversion.

2023-02-08 10:27 UTC, machi1990 commented
> > > @machi1990 do you suspect that a private network will be the default? the reason I have that as is, is that I presumed public would be default. This was also mentioned by Keith Wall. I'm easy either way really.
> > 
> > 
> > Hi @dimakis there is a bug in that logic which I highlighted. If someone choose to allow for private kafkas - i.e `accessKafkasViaPublicNetwork set to "true"` then with the logic current in place, it'll send the value as `false`. And vice versa.
> 
> @machi1990 It is not a bug, its a feature stuck_out_tongue The wording is changed to public, i.e. `would you like your kafkas to have access to a public network` hence the inversion.
> 
> it is a little confusing yes, as the var in the endpoint is `private`

Right. That's confusing. And the fact that it defaults to `no` public access is also confusing.

2023-02-08 10:39 UTC, machi1990 commented on pkg/cmd/dedicated/register/registercluster.go
>  		opts.accessKafkasViaPrivateNetwork = false
```suggestion
opts.accessKafkasViaPrivateNetwork = !accessFromPublicNetwork
```

2023-02-08 10:41 UTC, machi1990 commented on pkg/cmd/dedicated/register/registercluster.go
>  	}
```suggestion
```

2023-02-08 10:42 UTC, machi1990 commented on pkg/cmd/dedicated/register/registercluster.go
>  	}
trailing brace

2023-02-13 06:32 UTC, rkpattnaik780 commented on pkg/core/localize/locales/en/cmd/dedicated.en.toml
> +one = 'Would you like your Kafkas to be accessible via a public network?'
Wondering if we should use `Kafka instances` instead of `Kafkas`

2023-02-21 11:56 UTC, jackdelahunt commented
Closed because work is done in other pr #1794

2023-02-21 11:56 UTC, closed without merging