refactor: Refactor ocm methods out of register cmd file
redhat-developer/app-services-cli pull request #1807
Opened 2023-02-13 09:45 UTC by dimakis

Closes # 

### Verification Steps

1. Do x
2. Do y

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change
- [ ] Other (please specify)

2023-02-13 10:24 UTC, rkpattnaik780 reviewed
Looks good! Dropped some minor suggestions.

2023-02-13 10:24 UTC, rkpattnaik780 commented on pkg/shared/connection/api/clustermgmt/ocmfuncs.go
> +package clustermgmt
Maybe we should have this file as `ocm_util`? Wdyt?

2023-02-13 10:24 UTC, rkpattnaik780 commented on pkg/shared/connection/api/clustermgmt/ocmfuncs.go
> +	client, cc, err := conn.API().OCMClustermgmt(clustermgmturl, accessToken)
`cc` doesn't feel very descriptive, can we think of some other variable name?

2023-02-14 09:50 UTC, andreaTP requested changes
A couple of suggestions, the main issue is the lack of tests 🙁

2023-02-14 09:50 UTC, andreaTP commented on pkg/shared/connection/api/clustermgmt/ocmfuncs.go
> +	// TO-DO deal with pagination, validate clusters -- must be multi AZ and ready.
I think that this TODO should be tackled

2023-02-14 09:50 UTC, andreaTP commented on pkg/shared/connection/api/clustermgmt/ocmfuncs.go
> +	conn, err := f.Connection()
the following lines until `defer cc()` are repeated multiple times, can they be refactored?

2023-02-16 06:22 UTC, rkpattnaik780 approved these changes

2023-02-16 06:22 UTC, rkpattnaik780 commented on pkg/cmd/dedicated/register/registercluster.go
> +	pageNumber                    int
nitpick: Suggesting to use variable names `page` and `size`, since that's what we use for most of the commands.

2023-02-20 10:42 UTC, merged

2023-02-21 06:13 UTC, rkpattnaik780 commented on pkg/cmd/dedicated/register/registercluster.go
> +	flags.IntVar(&opts.pageSize, "page-size", 100, f.Localizer.MustLocalize("dedicated.registerCluster.flag.pageSize.description"))
Struck me while reviewing a different PR, why is the page size 100 here?
Can we use `buid.defaultpagesize` here? 100 might be too large.