SRS Management CLI
redhat-developer/app-services-cli pull request #691
Opened 2021-05-25 11:26 UTC by wtrocki

More refined version of POC PR #667. 

## Progresss

- This PR implements CRUD capabilities for srs backend.
- I have addressed all features making the experience with Kafka and service registry almost the same. 

## Outstanding work

- Backend doesn't support ` like ` search so we created separate issue #756 

## Verification

We should use both mock (for testing corner cases) and stage

```
rhoas login --api-gateway=stage
```

```
rhoas login --api-gateway=http://localhost:8000
```

Enable dev mode:
```
rhoas --devpreview=true 
```

Execute all registry commands
```
Create new Service Registry instances and interact with them by creating artifacts and downloading them to your machine

Usage:
  rhoas registry [command]

Examples:
## Create Service Registry
rhoas registry create --name=myregistry

## List registry
rhoas registry list 

Available Commands:
  create      Create Service Registry
  delete      Delete Service Registry
  describe    Describe Service Registry instance
  list        List service registries
  use         Use Service Registry

Global Flags:
  -d, --debug   Enable debug mode
  -h, --help    Show help for a command
```

## Addressing code repetition

I think it is too early to wrap both services and make them generic. 
While code seems to be repeated it will be actually much easier to have some form of repetition rather than generic interface that will block other services.

2021-06-29 16:30 UTC, wtrocki commented
ping @jbyrne-redhat  for language review

2021-06-29 18:26 UTC, wtrocki commented
As agreed support for status and cluster commands will be added in separate PRs as there will be problem with affecting current kafka implementation

2021-06-29 18:30 UTC, wtrocki commented
Documentation will be generated after review

2021-06-30 08:32 UTC, rkpattnaik780 requested changes
![Screenshot from 2021-06-30 14-00-50](https://user-images.githubusercontent.com/23582438/123928605-b1c45080-d9ab-11eb-976f-10c7bad07cd7.png)

Upon deleting in interactive mode, user should provide the ID as well, else things become troublesome when we have two registries with same name.

Also should the owner column be removed from registry list?

2021-06-30 08:32 UTC, rkpattnaik780 commented on internal/config/type.go
> +// KafkaConfig is the config for the Kafka service
Wrong docstring

2021-06-30 08:32 UTC, rkpattnaik780 commented on pkg/localize/locales/en/cmd/registry_crud.en.toml
> +one = 'Please provide name of Service Registry'
Should we just change it to "Name of service registry", followed by colon?

2021-06-30 08:58 UTC, wtrocki commented
> Upon deleting in interactive mode, user should provide the ID as well, else things become troublesome when we have two registries with same name.

SRS registries will have unique name. SRS backend is still missing some bits comparing to kafka.
Here is issue:
https://github.com/bf2fc6cc711aee1a0c2a/srs-fleet-manager/issues/75

2021-06-30 09:03 UTC, wtrocki commented
FYI @jsenko this is the SRS-fleetshard CLI integration

2021-06-30 09:41 UTC, jbyrne-redhat commented
> ping @jbyrne-redhat for language review

ACK @wtrocki. Let me bring this up for discussion with the CCS team and see who might work on this.

2021-06-30 10:40 UTC, craicoverflow commented
Needs a rebase.

2021-06-30 10:51 UTC, wtrocki commented
@craicoverflow Doing rebase now

2021-06-30 11:22 UTC, wtrocki commented
Rebased and Reverified all the changes

2021-06-30 11:43 UTC, wtrocki commented
Looking for review

2021-06-30 11:46 UTC, wtrocki commented
I cannot figure out why check-docs fails.

```
git diff --stat docs/commands | wc -l
``` 

returns 0

2021-06-30 12:05 UTC, craicoverflow approved these changes
Review complete and tested this out on staging. The two things I am unsure about are:

- "registry" command name. I think we should call it "service-registry"
- The way to configure devpreview is a little strange. It may need a revisit.

Approving

2021-06-30 12:08 UTC, wtrocki commented on pkg/cmd/ams/ams.go
> +		return false, "", errors.New("terms must be signed, but there is no terms URL")
Will do. I have copied that original source code that weren't localized and forgot to localize it.

2021-06-30 12:09 UTC, wtrocki commented on pkg/cmd/registry/create/create.go
> +		data, _ := json.MarshalIndent(response, "", cmdutil.DefaultJSONIndent)
This is copy paste from Kafka. Will fix in two places?

2021-06-30 12:11 UTC, wtrocki commented on pkg/cmd/registry/registry.go
> +		Use:         "registry",
other companies have the same name in cli. WE have serviceaccounts that will clash so registry is the best name from ux point of view.

2021-06-30 12:13 UTC, wtrocki commented on pkg/cmd/root/root.go
> +	cmd.Flags().StringVarP(&devpreview, "devpreview", "", "", f.Localizer.MustLocalize("root.cmd.flag.devpreview.description"))
Boolean cannot have 3 states - Not set, True or False. We need 3 states in our implementation.

2021-06-30 12:13 UTC, wtrocki commented on pkg/cmd/root/root.go
> +			_, err := profile.EnableDevPreview(f, &devpreview)
Agreed and we have issue to create this command already

2021-06-30 12:21 UTC, rkpattnaik780 approved these changes

2021-06-30 12:22 UTC, craicoverflow commented on pkg/cmd/root/root.go
> +	cmd.Flags().StringVarP(&devpreview, "devpreview", "", "", f.Localizer.MustLocalize("root.cmd.flag.devpreview.description"))
Isn't "Not set" the same as false?

2021-06-30 12:25 UTC, craicoverflow commented on pkg/cmd/registry/registry.go
> +		Use:         "registry",
What other companies?

Confluent uses `confluent schema-registry`.

> WE have serviceaccounts cmd that people might be also confused with - so registry is the best name from ux point of view.

Hmm..not sure if I agree. `serviceaccounts` are for managing accounts for different services, `service-registry` is for managing registries for different services. Customers who buy RHOSAK will know about the Service Registry service which comes for free so they will fully understand what `service-registry` is.

2021-06-30 12:36 UTC, wtrocki commented on pkg/cmd/root/root.go
> +	cmd.Flags().StringVarP(&devpreview, "devpreview", "", "", f.Localizer.MustLocalize("root.cmd.flag.devpreview.description"))
False means set it to false. Not set means do nothing. Since you have suggested dedicated command do we need to improve current implementation?

2021-06-30 13:04 UTC, craicoverflow commented on pkg/cmd/root/root.go
> +	cmd.Flags().StringVarP(&devpreview, "devpreview", "", "", f.Localizer.MustLocalize("root.cmd.flag.devpreview.description"))
Why would a user specify `--devpreview` if it does nothing? What would be the reason for that? It is almost always the case that not passing a value for a truthy flag defaults it to true - users will expect this to be the same.

2021-06-30 13:05 UTC, craicoverflow commented on pkg/cmd/root/root.go
> +	cmd.Flags().StringVarP(&devpreview, "devpreview", "", "", f.Localizer.MustLocalize("root.cmd.flag.devpreview.description"))
I don't want to let it block this PR from being merged, I think we can improve implementation again before the next stable release.

2021-06-30 14:23 UTC, jbyrne-redhat commented on pkg/localize/locales/en/cmd/registry_crud.en.toml
> +Create new Service Registry instances and interact with them by creating artifacts and downloading them to your machine
@craicoverflow I think "computer" is the best term here. The IBM Style Guide recommends against "machine" unless it is a virtual machine.

2021-06-30 14:33 UTC, wtrocki commented on pkg/localize/locales/en/cmd/registry_crud.en.toml
> +Create new Service Registry instances and interact with them by creating artifacts and downloading them to your machine
```suggestion
Create new Service Registry instances and interact with them by creating artifacts and downloading them to your computer
```

2021-06-30 14:36 UTC, wtrocki commented on pkg/cmd/registry/registry.go
> +		Use:         "registry",
I ment:

- mixing commands with and without `-` will be confusing
- can do serviceregistry for you (this was there initially but I ended up calling serviceaccounts by mistake)

2021-06-30 14:40 UTC, wtrocki commented on pkg/arguments/arguments.go
> +func EnableDevPreview(f *factory.Factory, enablement *string) (*config.Config, error) {
We need couple things from factory including logger, config etc.

2021-06-30 14:42 UTC, wtrocki commented on pkg/arguments/arguments.go
> +	config.DevPreviewEnabled = strings.ToLower(*enablement) == "true" || *enablement == "yes" || *enablement == "y"
This one returns error. I want to handle yes etc.

2021-06-30 16:17 UTC, merged

2021-07-01 13:41 UTC, smccarthy-ie commented
@wtrocki @jbyrne-redhat I can follow up with a fresh PR for the contents the .adoc files.

2021-07-01 14:00 UTC, wtrocki commented
@smccarthy-ie Thank you. Sorry for premature merge. All contents should be in the service-registry-* files so it will be simple to fix them on main.

2021-07-01 14:24 UTC, smccarthy-ie commented
@wtrocki No worries, nothing too controversial here, just some minor tidy up. Nice way for me to start getting familiar with the app services world :)