fix: minor bug fixes and validations
redhat-developer/app-services-cli pull request #696
Opened 2021-06-01 11:48 UTC by rkpattnaik780

Closes #693, #694, #695

### Verification Steps

1. Do x
2. Do y

### Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change
- [ ] Other (please specify)

### Checklist

- [ ] Documentation added for the feature
- [ ] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

2021-06-01 11:51 UTC, rkpattnaik780 commented on pkg/kafka/kafka_util.go
> +		_, httpRes, _ := GetKafkaByName(context.Background(), api, name)
Getting a lint error here with the message: `response body must be closed (bodyclose)`. Calling close() method does remove this message but causes other issues. Any suitable workaround for this is appreciated.

2021-06-01 13:01 UTC, craicoverflow requested changes
Missing verification steps made it a bit more difficult o verify quickly

Overall, the changes are great, but a couple of small changes are required.

2021-06-01 14:11 UTC, rkpattnaik780 commented on pkg/kafka/kafka_util.go
> +			return errors.New("kafka cluster name is already used")
Non-interactive mode returns `Kafka cluster` (error message from server).
![Screenshot from 2021-06-01 19-34-47](https://user-images.githubusercontent.com/23582438/120337510-01fab500-c311-11eb-83a7-538854e2e79a.png)
It should be changed either from the API first or should we define a set of error messages for each status code(as done for `kafka topic`)?

2021-06-01 14:18 UTC, craicoverflow commented on pkg/kafka/kafka_util.go
> +			return errors.New("kafka cluster name is already used")
We should do the latter. We probably do not need to do it for all of them yet, but for this one we should yeah.

2021-06-02 11:31 UTC, craicoverflow approved these changes

2021-06-03 08:07 UTC, merged